receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  filter/healthcheck:
    spans:
      exclude:
        match_type: strict
        attributes:
          - Key: http.target
            Value: /health

exporters:
  azuremonitor:
    instrumentation_key: "$APP_INSIGHTS_KEY"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,filter/healthcheck]
      exporters: [azuremonitor]
